### ISSUE TITLE
Eksiklikler

### ISSUE THREAD

**Issue by fstasel** [CankayaUniversity/ceng-407-408-2021-2022-Cryptocurrency-Portfolio-Tracker#3]
Kodlar yok!!
Wikide test plan and results sayfası yok
Wikide 408 proje raporu pdf halinde link yok
Proje raporunun spiralli çıktısı tracking formlar ile teslim edilmedi!

**Comment by fstasel** [comment]
Eksiklikler tamamlanmazsa dersten kalabilirsiniz!

**Comment by sanberkzulfikar** [comment]
Belirttiğiniz tüm eksiklikleri tamamladık hocam. Teşekkür ederiz.
